export const flights = {
  OTA_AirDetailsRS: {
    PrimaryLangID: 'eng',
    Version: '1.0',
    TransactionIdentifier: '',
    FLSNote: 'This XML adds attributes not in the OTA XML spec.  All such attributes start with FLS',
    FLSDevice: 'otaxmlexpanded',
    xmlns: 'http://www.opentravel.org/OTA/2003/05',
    Success: {
      selfclosing: 'true',
    },
    FLSResponseFields: {
      FLSOriginCode: 'PNQ',
      FLSOriginName: 'Lohegaon Airport',
      FLSDestinationCode: 'PAT',
      FLSDestinationName: 'Jayaprakash Narayan Airport',
      FLSStartDate: '20221222',
      FLSEndDate: '20221222',
      FLSResultCount: '3',
      FLSRoutesFound: '10',
      FLSBranchCount: '95',
      FLSTargetCount: '107',
      FLSRecordCount: '6635',
      selfclosing: 'true',
    },
    FlightDetails: [
      {
        TotalFlightTime: 'PT3H35M',
        TotalMiles: '1253',
        TotalTripTime: 'PT4H15M',
        FLSDepartureDateTime: '20221222T05:30:00',
        FLSDepartureTimeOffset: '+0530',
        FLSDepartureCode: 'PNQ',
        FLSDepartureName: 'Lohegaon Airport',
        FLSArrivalDateTime: '20221222T09:45:00',
        FLSArrivalTimeOffset: '+0530',
        FLSArrivalCode: 'PAT',
        FLSArrivalName: 'Jayaprakash Narayan Airport',
        FLSFlightType: 'Connect',
        FLSFlightLegs: '2',
        FLSFlightDays: '...4...',
        FLSDayIndicator: '',
        FlightLegDetails: [
          {
            DepartureDateTime: '20221222T05:30:00',
            FLSDepartureTimeOffset: '+0530',
            ArrivalDateTime: '20221222T07:40:00',
            FLSArrivalTimeOffset: '+0530',
            FlightNumber: '974',
            JourneyDuration: 'PT2H10M',
            SequenceNumber: '1',
            LegDistance: '720',
            FLSMeals: 'M',
            FLSInflightServices: ' ',
            FLSUUID: 'PNQDEL20221222UK974',
            DepartureAirport: {
              CodeContext: 'IATA',
              LocationCode: 'PNQ',
              FLSLocationName: 'Lohegaon Airport',
              Terminal: ' ',
              FLSDayIndicator: '"/',
              selfclosing: 'true',
            },
            ArrivalAirport: {
              CodeContext: 'IATA',
              LocationCode: 'DEL',
              FLSLocationName: 'Indira Gandhi International Airport',
              Terminal: '3',
              FLSDayIndicator: '"/',
              selfclosing: 'true',
            },
            MarketingAirline: {
              Code: 'UK',
              CodeContext: 'IATA',
              CompanyShortName: 'Vistara',
              selfclosing: 'true',
            },
            Equipment: {
              AirEquipType: '320',
              selfclosing: 'true',
            },
          },
          {
            DepartureDateTime: '20221222T08:20:00',
            FLSDepartureTimeOffset: '+0530',
            ArrivalDateTime: '20221222T09:45:00',
            FLSArrivalTimeOffset: '+0530',
            FlightNumber: '717',
            JourneyDuration: 'PT1H25M',
            SequenceNumber: '2',
            LegDistance: '533',
            FLSMeals: 'M',
            FLSInflightServices: ' ',
            FLSUUID: 'DELPAT20221222UK717',
            DepartureAirport: {
              CodeContext: 'IATA',
              LocationCode: 'DEL',
              FLSLocationName: 'Indira Gandhi International Airport',
              Terminal: '3',
              FLSDayIndicator: '"/',
              selfclosing: 'true',
            },
            ArrivalAirport: {
              CodeContext: 'IATA',
              LocationCode: 'PAT',
              FLSLocationName: 'Jayaprakash Narayan Airport',
              Terminal: ' ',
              FLSDayIndicator: '"/',
              selfclosing: 'true',
            },
            MarketingAirline: {
              Code: 'UK',
              CodeContext: 'IATA',
              CompanyShortName: 'Vistara',
              selfclosing: 'true',
            },
            Equipment: {
              AirEquipType: '320',
              selfclosing: 'true',
            },
          },
        ],
      },
      {
        TotalFlightTime: 'PT2H15M',
        TotalMiles: '864',
        TotalTripTime: 'PT2H15M',
        FLSDepartureDateTime: '20221222T12:05:00',
        FLSDepartureTimeOffset: '+0530',
        FLSDepartureCode: 'PNQ',
        FLSDepartureName: 'Lohegaon Airport',
        FLSArrivalDateTime: '20221222T14:20:00',
        FLSArrivalTimeOffset: '+0530',
        FLSArrivalCode: 'PAT',
        FLSArrivalName: 'Jayaprakash Narayan Airport',
        FLSFlightType: 'NonStop',
        FLSFlightLegs: '1',
        FLSFlightDays: '...4...',
        FLSDayIndicator: '',
        FlightLegDetails: {
          DepartureDateTime: '20221222T12:05:00',
          FLSDepartureTimeOffset: '+0530',
          ArrivalDateTime: '20221222T14:20:00',
          FLSArrivalTimeOffset: '+0530',
          FlightNumber: '757',
          JourneyDuration: 'PT2H15M',
          SequenceNumber: '1',
          LegDistance: '864',
          FLSMeals: '',
          FLSInflightServices: ' ',
          FLSUUID: 'PNQPAT20221222SG757',
          DepartureAirport: {
            CodeContext: 'IATA',
            LocationCode: 'PNQ',
            FLSLocationName: 'Lohegaon Airport',
            Terminal: ' ',
            FLSDayIndicator: '"/',
            selfclosing: 'true',
          },
          ArrivalAirport: {
            CodeContext: 'IATA',
            LocationCode: 'PAT',
            FLSLocationName: 'Jayaprakash Narayan Airport',
            Terminal: ' ',
            FLSDayIndicator: '"/',
            selfclosing: 'true',
          },
          MarketingAirline: {
            Code: 'SG',
            CodeContext: 'IATA',
            CompanyShortName: 'SpiceJet',
            selfclosing: 'true',
          },
          Equipment: {
            AirEquipType: '737',
            selfclosing: 'true',
          },
        },
      },
      {
        TotalFlightTime: 'PT2H20M',
        TotalMiles: '864',
        TotalTripTime: 'PT2H20M',
        FLSDepartureDateTime: '20221222T16:40:00',
        FLSDepartureTimeOffset: '+0530',
        FLSDepartureCode: 'PNQ',
        FLSDepartureName: 'Lohegaon Airport',
        FLSArrivalDateTime: '20221222T19:00:00',
        FLSArrivalTimeOffset: '+0530',
        FLSArrivalCode: 'PAT',
        FLSArrivalName: 'Jayaprakash Narayan Airport',
        FLSFlightType: 'NonStop',
        FLSFlightLegs: '1',
        FLSFlightDays: '...4...',
        FLSDayIndicator: '',
        FlightLegDetails: {
          DepartureDateTime: '20221222T16:40:00',
          FLSDepartureTimeOffset: '+0530',
          ArrivalDateTime: '20221222T19:00:00',
          FLSArrivalTimeOffset: '+0530',
          FlightNumber: '653',
          JourneyDuration: 'PT2H20M',
          SequenceNumber: '1',
          LegDistance: '864',
          FLSMeals: 'F',
          FLSInflightServices: ' ',
          FLSUUID: 'PNQPAT202212226E653',
          DepartureAirport: {
            CodeContext: 'IATA',
            LocationCode: 'PNQ',
            FLSLocationName: 'Lohegaon Airport',
            Terminal: ' ',
            FLSDayIndicator: '"/',
            selfclosing: 'true',
          },
          ArrivalAirport: {
            CodeContext: 'IATA',
            LocationCode: 'PAT',
            FLSLocationName: 'Jayaprakash Narayan Airport',
            Terminal: ' ',
            FLSDayIndicator: '"/',
            selfclosing: 'true',
          },
          MarketingAirline: {
            Code: '6E',
            CodeContext: 'IATA',
            CompanyShortName: 'IndiGo',
            selfclosing: 'true',
          },
          Equipment: {
            AirEquipType: '320',
            selfclosing: 'true',
          },
        },
      },
    ],
  },
};

export const airports = [
  {
    iataCode: 'AGR',
    country: 'IN',
    state: 'UP',
    city: '',
    airportName: 'Agra Airport',
    latitude: '27.158',
    longitude: '77.963',
  },
  {
    iataCode: 'AGX',
    country: 'IN',
    state: 'LD',
    city: '',
    airportName: 'Agatti Island Airport',
    latitude: '10.824',
    longitude: '72.176',
  },
  {
    iataCode: 'AJL',
    country: 'IN',
    state: 'MZ',
    city: '',
    airportName: 'Lengpui Airport',
    latitude: '23.839',
    longitude: '92.625',
  },
  {
    iataCode: 'AMD',
    country: 'IN',
    state: 'GJ',
    city: '',
    airportName: 'Sardar VallabhBhai Patel Airport',
    latitude: '23.066',
    longitude: '72.624',
  },
  {
    iataCode: 'ATQ',
    country: 'IN',
    state: 'PB',
    city: '',
    airportName: 'Sri Guru Ram Dass Jee Airport',
    latitude: '31.71',
    longitude: '74.797',
  },
  {
    iataCode: 'BBI',
    country: 'IN',
    state: 'OR',
    city: '',
    airportName: 'Biju Patnaik Airport',
    latitude: '20.244',
    longitude: '85.82',
  },
  {
    iataCode: 'BDQ',
    country: 'IN',
    state: 'GJ',
    city: '',
    airportName: 'Vadodara Airport',
    latitude: '22.329',
    longitude: '73.221',
  },
  {
    iataCode: 'BEK',
    country: 'IN',
    state: 'UP',
    city: '',
    airportName: 'Bareilly Airport',
    latitude: '26.217',
    longitude: '81.233',
  },
  {
    iataCode: 'BHJ',
    country: 'IN',
    state: 'GJ',
    city: '',
    airportName: 'Shyamji Krishna Verma Airport',
    latitude: '23.288',
    longitude: '69.671',
  },
  {
    iataCode: 'BHO',
    country: 'IN',
    state: 'MP',
    city: '',
    airportName: 'Raja Bhoj Airport',
    latitude: '23.285',
    longitude: '77.339',
  },
  {
    iataCode: 'BHU',
    country: 'IN',
    state: 'GJ',
    city: '',
    airportName: 'Bhavnagar Airport',
    latitude: '21.755',
    longitude: '72.184',
  },
  {
    iataCode: 'BKB',
    country: 'IN',
    state: 'RJ',
    city: '',
    airportName: 'Nal Airport',
    latitude: '28.017',
    longitude: '73.3',
  },
  {
    iataCode: 'BLR',
    country: 'IN',
    state: 'KA',
    city: '',
    airportName: 'Kempegowda International Airport',
    latitude: '13.199',
    longitude: '77.706',
  },
  {
    iataCode: 'BOM',
    country: 'IN',
    state: 'MH',
    city: '',
    airportName: 'Chhatrapati Shivaji Maharaj Airport',
    latitude: '19.088',
    longitude: '72.852',
  },
  {
    iataCode: 'CCJ',
    country: 'IN',
    state: 'KL',
    city: '',
    airportName: 'Kozhikode International Airport',
    latitude: '11.137',
    longitude: '75.951',
  },
  {
    iataCode: 'CCU',
    country: 'IN',
    state: 'WB',
    city: '',
    airportName: 'Subhas Chandra Bose Airport',
    latitude: '22.652',
    longitude: '88.449',
  },
  {
    iataCode: 'CDP',
    country: 'IN',
    state: 'AP',
    city: '',
    airportName: 'Cuddapah Airport',
    latitude: '14.517',
    longitude: '78.783',
  },
  {
    iataCode: 'CJB',
    country: 'IN',
    state: 'TN',
    city: '',
    airportName: 'Coimbatore International Airport',
    latitude: '11.028',
    longitude: '77.043',
  },
  {
    iataCode: 'CNN',
    country: 'IN',
    state: 'KL',
    city: '',
    airportName: 'Kannur International Airport',
    latitude: '11.918',
    longitude: '75.546',
  },
  {
    iataCode: 'COH',
    country: 'IN',
    state: 'WB',
    city: '',
    airportName: 'Cooch Behar Airport',
    latitude: '26.333',
    longitude: '89.467',
  },
  {
    iataCode: 'COK',
    country: 'IN',
    state: 'KL',
    city: '',
    airportName: 'Kochi International Airport',
    latitude: '10.156',
    longitude: '76.39',
  },
  {
    iataCode: 'DBR',
    country: 'IN',
    state: 'BR',
    city: '',
    airportName: 'Darbhanga Airport',
    latitude: '26.198',
    longitude: '85.911',
  },
  {
    iataCode: 'DED',
    country: 'IN',
    state: 'UT',
    city: '',
    airportName: 'Jolly Grant Airport',
    latitude: '30.19',
    longitude: '78.18',
  },
  {
    iataCode: 'DEL',
    country: 'IN',
    state: 'DL',
    city: '',
    airportName: 'Indira Gandhi International Airport',
    latitude: '28.574',
    longitude: '77.101',
  },
  {
    iataCode: 'DGH',
    country: 'IN',
    state: 'JH',
    city: '',
    airportName: 'Deoghar International Airport',
    latitude: '24.447',
    longitude: '86.707',
  },
  {
    iataCode: 'DHM',
    country: 'IN',
    state: 'HP',
    city: '',
    airportName: 'Kangra Airport',
    latitude: '32.165',
    longitude: '76.26',
  },
  {
    iataCode: 'DIB',
    country: 'IN',
    state: 'AS',
    city: '',
    airportName: 'Mohanbari Airport',
    latitude: '27.484',
    longitude: '95.021',
  },
  {
    iataCode: 'DIU',
    country: 'IN',
    state: 'DD',
    city: '',
    airportName: 'Diu Airport',
    latitude: '20.717',
    longitude: '70.917',
  },
  {
    iataCode: 'DMU',
    country: 'IN',
    state: 'NL',
    city: '',
    airportName: 'Dimapur Airport',
    latitude: '25.884',
    longitude: '93.774',
  },
  {
    iataCode: 'GAU',
    country: 'IN',
    state: 'AS',
    city: '',
    airportName: 'Gopinath Bordoloi International Airport',
    latitude: '26.104',
    longitude: '91.588',
  },
  {
    iataCode: 'GAY',
    country: 'IN',
    state: 'BR',
    city: '',
    airportName: 'Gaya Airport',
    latitude: '24.747',
    longitude: '84.946',
  },
  {
    iataCode: 'GBI',
    country: 'IN',
    state: 'KA',
    city: '',
    airportName: 'Kalaburagi Airport',
    latitude: '17.31',
    longitude: '76.92',
  },
  {
    iataCode: 'GOI',
    country: 'IN',
    state: 'GA',
    city: '',
    airportName: 'Dabolim Airport',
    latitude: '15.381',
    longitude: '73.831',
  },
  {
    iataCode: 'GOP',
    country: 'IN',
    state: 'UP',
    city: '',
    airportName: 'Gorakhpur Airport',
    latitude: '26.74',
    longitude: '83.45',
  },
  {
    iataCode: 'GOX',
    country: 'IN',
    state: 'GA',
    city: '',
    airportName: 'Mopa Airport',
    latitude: '15.731',
    longitude: '73.868',
  },
  {
    iataCode: 'GWL',
    country: 'IN',
    state: 'MP',
    city: '',
    airportName: 'Gwalior Airport',
    latitude: '26.294',
    longitude: '78.23',
  },
  {
    iataCode: 'HBX',
    country: 'IN',
    state: 'KA',
    city: '',
    airportName: 'Hubli Airport',
    latitude: '15.361',
    longitude: '75.086',
  },
  {
    iataCode: 'HGI',
    country: 'IN',
    state: 'AR',
    city: '',
    airportName: 'Hollongi Airport',
    latitude: '26.966',
    longitude: '93.651',
  },
  {
    iataCode: 'HJR',
    country: 'IN',
    state: 'MP',
    city: '',
    airportName: 'Khajuraho Airport',
    latitude: '24.824',
    longitude: '79.923',
  },
  {
    iataCode: 'HYD',
    country: 'IN',
    state: 'TG',
    city: '',
    airportName: 'Rajiv Gandhi International Airport',
    latitude: '17.26',
    longitude: '78.397',
  },
  {
    iataCode: 'IDR',
    country: 'IN',
    state: 'MP',
    city: '',
    airportName: 'Devi Ahilya Bai Holkar Airport',
    latitude: '22.723',
    longitude: '75.806',
  },
  {
    iataCode: 'IMF',
    country: 'IN',
    state: 'MN',
    city: '',
    airportName: 'Imphal Airport',
    latitude: '24.767',
    longitude: '93.9',
  },
  {
    iataCode: 'ISK',
    country: 'IN',
    state: 'MH',
    city: '',
    airportName: 'Ozar Airport',
    latitude: '20.119',
    longitude: '73.913',
  },
  {
    iataCode: 'IXA',
    country: 'IN',
    state: 'TR',
    city: '',
    airportName: 'Agartala Airport',
    latitude: '23.887',
    longitude: '91.241',
  },
  {
    iataCode: 'IXB',
    country: 'IN',
    state: 'WB',
    city: '',
    airportName: 'Bagdogra Airport',
    latitude: '26.683',
    longitude: '88.333',
  },
  {
    iataCode: 'IXC',
    country: 'IN',
    state: 'CH',
    city: '',
    airportName: 'Chandigarh Airport',
    latitude: '30.672',
    longitude: '76.791',
  },
  {
    iataCode: 'IXD',
    country: 'IN',
    state: 'UP',
    city: '',
    airportName: 'Allahabad Airport',
    latitude: '25.44',
    longitude: '81.736',
  },
  {
    iataCode: 'IXE',
    country: 'IN',
    state: 'KA',
    city: '',
    airportName: 'Mangalore Airport',
    latitude: '12.964',
    longitude: '74.894',
  },
  {
    iataCode: 'IXG',
    country: 'IN',
    state: 'KA',
    city: '',
    airportName: 'Sambre Airport',
    latitude: '15.859',
    longitude: '74.618',
  },
  {
    iataCode: 'IXI',
    country: 'IN',
    state: 'AS',
    city: '',
    airportName: 'Lilabari Airport',
    latitude: '27.29',
    longitude: '94.089',
  },
  {
    iataCode: 'IXJ',
    country: 'IN',
    state: 'JK',
    city: '',
    airportName: 'Satwari Airport',
    latitude: '32.69',
    longitude: '74.839',
  },
  {
    iataCode: 'IXK',
    country: 'IN',
    state: 'GJ',
    city: '',
    airportName: 'Keshod Airport',
    latitude: '21.319',
    longitude: '70.271',
  },
  {
    iataCode: 'IXL',
    country: 'IN',
    state: 'JK',
    city: '',
    airportName: 'Kushok Bakula Rimpoche Airport',
    latitude: '34.167',
    longitude: '77.583',
  },
  {
    iataCode: 'IXM',
    country: 'IN',
    state: 'TN',
    city: '',
    airportName: 'Madurai Airport',
    latitude: '9.834',
    longitude: '78.093',
  },
  {
    iataCode: 'IXR',
    country: 'IN',
    state: 'JH',
    city: '',
    airportName: 'Birsa Munda Airport',
    latitude: '23.314',
    longitude: '85.324',
  },
  {
    iataCode: 'IXS',
    country: 'IN',
    state: 'AS',
    city: '',
    airportName: 'Kumbhirgram Airport',
    latitude: '24.913',
    longitude: '92.979',
  },
  {
    iataCode: 'IXT',
    country: 'IN',
    state: 'AR',
    city: '',
    airportName: 'Pasighat Airport',
    latitude: '28.017',
    longitude: '95.333',
  },
  {
    iataCode: 'IXU',
    country: 'IN',
    state: 'MH',
    city: '',
    airportName: 'Aurangabad Airport',
    latitude: '19.864',
    longitude: '75.401',
  },
  {
    iataCode: 'IXW',
    country: 'IN',
    state: 'JH',
    city: '',
    airportName: 'Sonari Airport',
    latitude: '22.813',
    longitude: '86.169',
  },
  {
    iataCode: 'IXY',
    country: 'IN',
    state: 'GJ',
    city: '',
    airportName: 'Kandla Airport',
    latitude: '23.111',
    longitude: '70.104',
  },
  {
    iataCode: 'IXZ',
    country: 'IN',
    state: 'AN',
    city: '',
    airportName: 'Veer Savarkar International Airport',
    latitude: '11.648',
    longitude: '92.744',
  },
  {
    iataCode: 'JAI',
    country: 'IN',
    state: 'RJ',
    city: '',
    airportName: 'Jaipur International Airport',
    latitude: '26.824',
    longitude: '75.812',
  },
  {
    iataCode: 'JDH',
    country: 'IN',
    state: 'RJ',
    city: '',
    airportName: 'Jodhpur Airport',
    latitude: '26.261',
    longitude: '73.048',
  },
  {
    iataCode: 'JGA',
    country: 'IN',
    state: 'GJ',
    city: '',
    airportName: 'Govardhanpur Airport',
    latitude: '22.463',
    longitude: '70.012',
  },
  {
    iataCode: 'JGB',
    country: 'IN',
    state: 'CT',
    city: '',
    airportName: 'Jagdalpur Airport',
    latitude: '19.067',
    longitude: '82.033',
  },
  {
    iataCode: 'JLR',
    country: 'IN',
    state: 'MP',
    city: '',
    airportName: 'Jabalpur Airport',
    latitude: '23.178',
    longitude: '80.052',
  },
  {
    iataCode: 'JRG',
    country: 'IN',
    state: '',
    city: '',
    airportName: 'Veer Surendra Sai Airport',
    latitude: '21.913',
    longitude: '84.05',
  },
  {
    iataCode: 'JRH',
    country: 'IN',
    state: 'AS',
    city: '',
    airportName: 'Rowriah Airport',
    latitude: '26.729',
    longitude: '94.178',
  },
  {
    iataCode: 'JSA',
    country: 'IN',
    state: 'RJ',
    city: '',
    airportName: 'Jaisalmer Airport',
    latitude: '26.917',
    longitude: '70.9',
  },
  {
    iataCode: 'KBK',
    country: 'IN',
    state: 'UP',
    city: '',
    airportName: 'Kushinagar lnternational Airport',
    latitude: '26.773',
    longitude: '83.896',
  },
  {
    iataCode: 'KJB',
    country: 'IN',
    state: 'AP',
    city: '',
    airportName: 'Kurnool Airport',
    latitude: '15.715',
    longitude: '78.178',
  },
  {
    iataCode: 'KLH',
    country: 'IN',
    state: 'MH',
    city: '',
    airportName: 'Kolhapur Airport',
    latitude: '16.667',
    longitude: '74.333',
  },
  {
    iataCode: 'KNU',
    country: 'IN',
    state: 'UP',
    city: '',
    airportName: 'Kanpur Airport',
    latitude: '26.403',
    longitude: '80.412',
  },
  {
    iataCode: 'KUU',
    country: 'IN',
    state: 'HP',
    city: '',
    airportName: 'Bhuntar Airport',
    latitude: '31.983',
    longitude: '77.1',
  },
  {
    iataCode: 'LKO',
    country: 'IN',
    state: 'UP',
    city: '',
    airportName: 'Chaudhary Charan Singh Airport',
    latitude: '26.761',
    longitude: '80.889',
  },
  {
    iataCode: 'MAA',
    country: 'IN',
    state: 'TN',
    city: '',
    airportName: 'Chennai International Airport',
    latitude: '12.994',
    longitude: '80.181',
  },
  {
    iataCode: 'MYQ',
    country: 'IN',
    state: 'KA',
    city: '',
    airportName: 'Mandakalli Airport',
    latitude: '12.23',
    longitude: '76.656',
  },
  {
    iataCode: 'NAG',
    country: 'IN',
    state: 'MH',
    city: '',
    airportName: 'Dr.Ambedkar International Airport',
    latitude: '21.092',
    longitude: '79.047',
  },
  {
    iataCode: 'PAB',
    country: 'IN',
    state: 'CT',
    city: '',
    airportName: 'Bilaspur Airport',
    latitude: '31.317',
    longitude: '76.833',
  },
  {
    iataCode: 'PAT',
    country: 'IN',
    state: 'BR',
    city: '',
    airportName: 'Jayaprakash Narayan Airport',
    latitude: '25.591',
    longitude: '85.09',
  },
  {
    iataCode: 'PGH',
    country: 'IN',
    state: 'UT',
    city: '',
    airportName: 'Pantnagar Airport',
    latitude: '29.032',
    longitude: '79.474',
  },
  {
    iataCode: 'PNQ',
    country: 'IN',
    state: 'MH',
    city: '',
    airportName: 'Lohegaon Airport',
    latitude: '18.581',
    longitude: '73.921',
  },
  {
    iataCode: 'PNY',
    country: 'IN',
    state: 'PY',
    city: '',
    airportName: 'Pondicherry Airport',
    latitude: '11.969',
    longitude: '79.81',
  },
  {
    iataCode: 'PYB',
    country: 'IN',
    state: 'OR',
    city: '',
    airportName: 'Jeypore Airport',
    latitude: '18.833',
    longitude: '82.633',
  },
  {
    iataCode: 'RAJ',
    country: 'IN',
    state: 'GJ',
    city: '',
    airportName: 'Rajkot Airport',
    latitude: '22.306',
    longitude: '70.781',
  },
  {
    iataCode: 'RDP',
    country: 'IN',
    state: 'WB',
    city: '',
    airportName: 'Kazi Nazrul Islam Airport',
    latitude: '23.624',
    longitude: '87.242',
  },
  {
    iataCode: 'RJA',
    country: 'IN',
    state: 'AP',
    city: '',
    airportName: 'Rajahmundry Airport',
    latitude: '17.11',
    longitude: '81.821',
  },
  {
    iataCode: 'RPR',
    country: 'IN',
    state: 'CT',
    city: '',
    airportName: 'Swami Vivekananda Airport',
    latitude: '21.18',
    longitude: '81.739',
  },
  {
    iataCode: 'RRK',
    country: 'IN',
    state: 'OR',
    city: '',
    airportName: 'Rourkela Airport',
    latitude: '22.257',
    longitude: '84.815',
  },
  {
    iataCode: 'RUP',
    country: 'IN',
    state: 'AS',
    city: '',
    airportName: 'Rupsi Airport',
    latitude: '26.15',
    longitude: '89.917',
  },
  {
    iataCode: 'SAG',
    country: 'IN',
    state: 'MH',
    city: '',
    airportName: 'Shirdi Airport',
    latitude: '19.694',
    longitude: '74.394',
  },
  {
    iataCode: 'SDW',
    country: 'IN',
    state: 'MH',
    city: '',
    airportName: 'Sindhudurg Airport',
    latitude: '16.003',
    longitude: '73.531',
  },
  {
    iataCode: 'SHL',
    country: 'IN',
    state: 'ML',
    city: '',
    airportName: 'Barapani Airport',
    latitude: '25.706',
    longitude: '91.975',
  },
  {
    iataCode: 'SLV',
    country: 'IN',
    state: 'HP',
    city: '',
    airportName: 'Shimla Airport',
    latitude: '31.117',
    longitude: '77.15',
  },
  {
    iataCode: 'STV',
    country: 'IN',
    state: 'GJ',
    city: '',
    airportName: 'SuratAirport',
    latitude: '21.114',
    longitude: '72.742',
  },
  {
    iataCode: 'SXR',
    country: 'IN',
    state: 'JK',
    city: '',
    airportName: 'Sheikh ul Alam Airport',
    latitude: '33.987',
    longitude: '74.774',
  },
  {
    iataCode: 'TCR',
    country: 'IN',
    state: 'TN',
    city: '',
    airportName: 'Tuticorin Airport',
    latitude: '8.724',
    longitude: '78.026',
  },
  {
    iataCode: 'TEI',
    country: 'IN',
    state: 'AR',
    city: '',
    airportName: 'Tezu Airport',
    latitude: '27.95',
    longitude: '96.133',
  },
  {
    iataCode: 'TEZ',
    country: 'IN',
    state: 'AS',
    city: '',
    airportName: 'Tezpur Airport',
    latitude: '26.711',
    longitude: '92.796',
  },
  {
    iataCode: 'TIR',
    country: 'IN',
    state: 'AP',
    city: '',
    airportName: 'Tirupati Airport',
    latitude: '13.633',
    longitude: '79.543',
  },
  {
    iataCode: 'TRV',
    country: 'IN',
    state: 'KL',
    city: '',
    airportName: 'Thiruvananthapuram International Airpor',
    latitude: '8.48',
    longitude: '76.92',
  },
  {
    iataCode: 'TRZ',
    country: 'IN',
    state: 'TN',
    city: '',
    airportName: 'Tiruchchirappalli Airport',
    latitude: '10.765',
    longitude: '78.713',
  },
  {
    iataCode: 'UDR',
    country: 'IN',
    state: 'RJ',
    city: '',
    airportName: 'Maharana Pratap Airport',
    latitude: '24.618',
    longitude: '73.896',
  },
  {
    iataCode: 'VDY',
    country: 'IN',
    state: 'KA',
    city: '',
    airportName: 'Jindal Airport',
    latitude: '15.172',
    longitude: '76.644',
  },
  {
    iataCode: 'VGA',
    country: 'IN',
    state: 'AP',
    city: '',
    airportName: 'Vijayawada Airport',
    latitude: '16.531',
    longitude: '80.797',
  },
  {
    iataCode: 'VNS',
    country: 'IN',
    state: 'UP',
    city: '',
    airportName: 'Lal Bahadur Shastri Airport',
    latitude: '25.452',
    longitude: '82.859',
  },
  {
    iataCode: 'VTZ',
    country: 'IN',
    state: 'AP',
    city: '',
    airportName: 'Vishakhapatnam Airport',
    latitude: '17.721',
    longitude: '83.225',
  },
  {
    iataCode: 'ZER',
    country: 'IN',
    state: 'AR',
    city: '',
    airportName: 'Ziro Airport',
    latitude: '27.633',
    longitude: '93.833',
  },
];
